#----------
#Written by: Joaquin Carbonell, Jigarjeet Mannan
#For: CMPT 201 Assignment 3
#Lab Instructor: Philip Mees
#Lecture Instructor: Philip Mees
#makefile purpose: Hold commands for Assignment 3 makefile compiling
#----------

CC = gcc
CFLAGS = -Wall -std=c99 -g


.PHONY: testing clean tar

clean:
	#rm something

tar: DESIGN.txt makefile dashboard.c DB.h DB.c DB_impl.h DB_impl.c PicnicTable.bin dbTest.c /testing